In [1]:
# Import necessary packages
import os
import numpy as np
import earthpy as et


In [2]:
# Download .txt with avg monthly precip (inches)
monthly_precip_url = 'https://ndownloader.figshare.com/files/12565616'
et.data.get_data(url=monthly_precip_url)

# Download .csv of precip data for 2002 and 2013 (inches)
precip_2002_2013_url = 'https://ndownloader.figshare.com/files/12707792'
et.data.get_data(url=precip_2002_2013_url)


'/Users/Jroldan001/earth-analytics/data/earthpy-downloads/monthly-precip-2002-2013.csv'

In [3]:
# Set working directory to earth-analytics
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))


In [4]:
# Import average monthly precip
fname = os.path.join("data", "earthpy-downloads",
                     "avg-monthly-precip.txt")

avg_monthly_precip = np.loadtxt(fname)

print(avg_monthly_precip)


[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [5]:
# Import monthly precip for 2002 and 2013
fname = os.path.join("data", "earthpy-downloads",
                     "monthly-precip-2002-2013.csv")

precip_2002_2013 = np.loadtxt(fname, delimiter=",")

print(precip_2002_2013)


[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [6]:
# Check shape
avg_monthly_precip.shape


(12,)

In [7]:
# Select the last element of 12 elements
avg_monthly_precip[11]


0.84

In [8]:
# Select the last element of the array
avg_monthly_precip[-1]


0.84

In [9]:
# Slice range from 3rd to 5th elements
print(avg_monthly_precip[2:5])


[1.85 2.93 3.05]


In [10]:
# Check shape
precip_2002_2013.shape


(2, 12)

In [11]:
# Select element in 2nd row, 3rd column
precip_2002_2013[1, 2]


1.72

In [12]:
# Select element in 2nd row, 12th column
precip_2002_2013[1, 11]


0.5

In [13]:
# Select element in last row, last column
precip_2002_2013[-1, -1]


0.5

In [14]:
# Select element in last row, last column
precip_2002_2013[-1, -1]


0.5

In [15]:
# Slice first two rows, first column
print(precip_2002_2013[0:2, 0:1])


[[1.07]
 [0.27]]


In [16]:
# Slice 2nd row, 2nd and 3rd columns
print(precip_2002_2013[1:2, 1:3])



[[1.13 1.72]]


In [17]:
# Slice first two rows, first two columns
print(precip_2002_2013[:2, :2])


[[1.07 0.44]
 [0.27 1.13]]
